packages:
  - 'shared/*'
  - 'fellspiral/*'
  - 'videobrowser/*'
  - 'audiobrowser/*'
  - 'print/*'
  - 'printsync/*'
  - 'budget/*'
  - 'test-go-app/tests'
  - 'mcp-common'
  - 'gh-workflow-mcp-server'
  - 'gh-issue-mcp-server'
  - 'wiggum-mcp-server'

# Allow these trusted packages to run their build scripts
# pnpm 10 blocks lifecycle scripts by default for security
onlyBuiltDependencies:
  - core-js
  - es5-ext
  - esbuild
  - protobufjs
  - 'test-app-scaffold-verification/tests'
