// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
)

func SyncProgress(sessionID string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-bg-elevated rounded-lg shadow-lg p-6\" hx-ext=\"sse\" sse-connect=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/api/sync/%s/stream", sessionID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/partials/sync_progress.templ`, Line: 11, Col: 61}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><div class=\"flex items-center justify-between mb-4\"><h2 class=\"text-xl font-semibold\">Sync in Progress</h2><button hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/api/sync/%s/cancel", sessionID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/partials/sync_progress.templ`, Line: 16, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" hx-target=\"#sync-progress\" hx-swap=\"innerHTML\" class=\"px-3 py-1 text-sm bg-error text-white rounded hover:bg-error-hover transition-colors\">Cancel</button></div><!-- Stats Grid --><div id=\"sync-stats\" class=\"grid grid-cols-4 gap-4 mb-6\" sse-swap=\"session\" hx-swap=\"innerHTML\"><div class=\"text-center\"><div class=\"text-2xl font-bold text-primary\">0</div><div class=\"text-sm text-text-secondary\">Discovered</div></div><div class=\"text-center\"><div class=\"text-2xl font-bold text-success\">0</div><div class=\"text-sm text-text-secondary\">Extracted</div></div><div class=\"text-center\"><div class=\"text-2xl font-bold text-secondary\">0</div><div class=\"text-sm text-text-secondary\">Uploaded</div></div><div class=\"text-center\"><div class=\"text-2xl font-bold text-error\">0</div><div class=\"text-sm text-text-secondary\">Errors</div></div></div><!-- Progress Bar --><div id=\"sync-progress-bar\" class=\"mb-4\" sse-swap=\"progress\"><div class=\"w-full bg-bg-surface rounded-full h-2.5\"><div class=\"bg-primary h-2.5 rounded-full shadow-glow-subtle transition-all\" style=\"width: 0%\"></div></div><div class=\"text-sm text-text-secondary mt-2\"><span id=\"current-operation\">Initializing...</span></div></div><!-- File List --><div class=\"mt-6\"><h3 class=\"font-semibold mb-3\">Files</h3><div id=\"file-list\" class=\"space-y-2 max-h-96 overflow-y-auto\" sse-swap=\"file\"><!-- Files will be added here via SSE --></div></div><!-- Complete Message --><div id=\"complete-message\" class=\"hidden mt-6 p-4 bg-success-muted border border-success rounded-lg\" sse-swap=\"complete\"><p class=\"text-success font-medium\">Sync completed successfully!</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func SyncCancelled() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"bg-bg-elevated rounded-lg shadow-lg p-6\"><div class=\"text-center py-8\"><h2 class=\"text-xl font-semibold text-text-primary mb-2\">Sync Cancelled</h2><p class=\"text-text-secondary\">The sync operation was cancelled.</p><button hx-get=\"/partials/sync/form\" hx-target=\"#sync-form\" hx-swap=\"innerHTML\" class=\"mt-4 px-4 py-2 bg-primary text-bg-base font-medium rounded hover:bg-primary-hover hover:shadow-glow-subtle transition-all\">Start New Sync</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
