// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/commons-systems/filesync"
)

func SyncMonitor(sessionID string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-bg-elevated rounded-lg shadow-lg p-6\" hx-ext=\"sse\" sse-connect=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/api/sync/%s/stream", sessionID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/partials/sync_monitor.templ`, Line: 12, Col: 61}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><!-- Header with title and Cancel button --><div class=\"flex items-center justify-between mb-4\"><h2 class=\"text-xl font-semibold text-text-primary\">Sync in Progress</h2><button hx-post=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/api/sync/%s/cancel", sessionID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/partials/sync_monitor.templ`, Line: 18, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" hx-target=\"#sync-monitor\" hx-swap=\"outerHTML\" class=\"btn btn--sm btn--danger\"><span>Cancel</span> <span class=\"htmx-indicator spinner spinner--sm\"></span></button></div><!-- Stats section --><div id=\"sync-stats\" sse-swap=\"session\" hx-swap=\"innerHTML\"><!-- Initial stats - will be replaced by SSE --><div class=\"grid grid-cols-4 gap-4 mb-6\"><div class=\"text-center\"><div class=\"text-2xl font-bold text-primary\">0</div><div class=\"text-sm text-text-secondary\">Discovered</div></div><div class=\"text-center\"><div class=\"text-2xl font-bold text-success\">0</div><div class=\"text-sm text-text-secondary\">Extracted</div></div><div class=\"text-center\"><div class=\"text-2xl font-bold text-secondary\">0</div><div class=\"text-sm text-text-secondary\">Uploaded</div></div><div class=\"text-center\"><div class=\"text-2xl font-bold text-error\">0</div><div class=\"text-sm text-text-secondary\">Errors</div></div></div></div><!-- Progress bar section --><div id=\"phase-indicator\" sse-swap=\"progress\" hx-swap=\"innerHTML\"><!-- Initial progress - will be replaced by SSE --><div class=\"mb-6\"><div class=\"w-full bg-bg-surface rounded-full h-2.5\"><div class=\"bg-primary h-2.5 rounded-full shadow-glow-subtle transition-all duration-slow\" style=\"width: 0%\"></div></div><div class=\"text-sm text-text-secondary mt-2\"><span>Initializing...</span></div></div></div><!-- Action buttons section --><div id=\"action-buttons\" class=\"flex gap-3 mb-6\" sse-swap=\"actions\" hx-swap=\"innerHTML\"><!-- Action buttons will be updated via SSE -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ActionButtons(sessionID, filesync.SessionStats{}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><!-- Trash message section (populated by trash-all action via OOB swap) --><div id=\"trash-message\" class=\"hidden\"><!-- Will be populated by trash-all handler via hx-swap-oob --></div><!-- File list container --><div class=\"mt-6\"><div class=\"flex items-center justify-between mb-3\"><h3 class=\"font-semibold text-text-primary\">Files</h3><label id=\"select-all-container\" class=\"hidden flex items-center gap-2 text-sm text-text-secondary\"><input type=\"checkbox\" id=\"select-all-extracted\" class=\"w-4 h-4 rounded border-bg-hover text-primary focus:ring-primary\" onchange=\"toggleAllExtracted()\"> <span>Select All Extracted</span></label></div><div id=\"file-list\" class=\"space-y-2 max-h-96 overflow-y-auto\" sse-swap=\"file\" hx-swap=\"beforeend\"><!-- Files will be added here via SSE with beforeend swap --></div></div><!-- Complete message section --><div id=\"complete-message\" class=\"hidden\" sse-swap=\"complete\" hx-swap=\"innerHTML\"><!-- Will be populated by SSE when complete --></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
