name: 'Validate Deployment URL'
description: 'Validates Firebase Hosting deployment URL from /tmp/deployment-url.txt'

outputs:
  url:
    description: 'The validated deployment URL'
    value: ${{ steps.validate.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Validate deployment URL
      id: validate
      shell: bash
      run: |
        set -euo pipefail

        # Validate deployment URL file exists
        if [ ! -f /tmp/deployment-url.txt ]; then
          echo "::error::Deployment script did not create URL file"
          exit 1
        fi

        # Read and validate URL
        URL=$(cat /tmp/deployment-url.txt)
        if [ -z "$URL" ]; then
          echo "::error::Deployment URL is empty"
          exit 1
        fi

        # Validate URL format - strict regex to prevent consecutive dots
        if ! echo "$URL" | grep -qE '^https://[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*\.web\.app$'; then
          echo "::error::Invalid deployment URL format: $URL"
          echo "::error::Expected format: https://<subdomain>.web.app (lowercase, no consecutive dots)"
          exit 1
        fi

        echo "url=${URL}" >> $GITHUB_OUTPUT
        echo "Deployed to: ${URL}"
