name: 'Create GitHub Deployment'
description: 'Creates a GitHub deployment with status updates'
inputs:
  environment:
    description: 'Deployment environment name'
    required: true
  environment_url:
    description: 'URL of the deployment'
    required: true
  site_name:
    description: 'Name of the site being deployed'
    required: true
  is_preview:
    description: 'Whether this is a preview deployment'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Create deployment and set status
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        SITE_NAME: ${{ inputs.site_name }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        set -euo pipefail

        # Build JSON payload with required_contexts: []
        TRANSIENT_ENV="${{ inputs.is_preview == 'true' }}"

        if [ "$TRANSIENT_ENV" = "true" ]; then
          PAYLOAD=$(jq -n \
            --arg ref "${{ github.event.pull_request.head.sha || github.sha }}" \
            --arg environment "${ENVIRONMENT}" \
            --arg description "Deploy ${SITE_NAME} to ${ENVIRONMENT}" \
            '{
              ref: $ref,
              environment: $environment,
              description: $description,
              auto_merge: false,
              required_contexts: [],
              transient_environment: true
            }')
        else
          PAYLOAD=$(jq -n \
            --arg ref "${{ github.event.pull_request.head.sha || github.sha }}" \
            --arg environment "${ENVIRONMENT}" \
            --arg description "Deploy ${SITE_NAME} to ${ENVIRONMENT}" \
            '{
              ref: $ref,
              environment: $environment,
              description: $description,
              auto_merge: false,
              required_contexts: []
            }')
        fi

        DEPLOYMENT_RESPONSE=$(gh api repos/${{ github.repository }}/deployments \
          -X POST \
          --input - <<< "$PAYLOAD")

        DEPLOYMENT_ID=$(echo "$DEPLOYMENT_RESPONSE" | jq -r '.id')

        if [ "$DEPLOYMENT_ID" = "null" ] || [ -z "$DEPLOYMENT_ID" ]; then
          echo "::error::Failed to create deployment"
          echo "$DEPLOYMENT_RESPONSE"
          exit 1
        fi

        gh api repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses \
          -X POST \
          -f state="success" \
          -f environment_url="${{ inputs.environment_url }}" \
          -f log_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f description="Deployment successful"
