name: 'Create GitHub Deployment'
description: 'Creates a GitHub deployment with status updates'
inputs:
  environment:
    description: 'Deployment environment name'
    required: true
  environment_url:
    description: 'URL of the deployment'
    required: true
  site_name:
    description: 'Name of the site being deployed'
    required: true
  is_preview:
    description: 'Whether this is a preview deployment'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Create deployment and set status
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        SITE_NAME: ${{ inputs.site_name }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        set -euo pipefail

        # Build JSON payload with required_contexts: []
        TRANSIENT_ENV="${{ inputs.is_preview == 'true' }}"

        if [ "$TRANSIENT_ENV" = "true" ]; then
          PAYLOAD=$(jq -n \
            --arg ref "${{ github.event.pull_request.head.sha || github.sha }}" \
            --arg environment "${ENVIRONMENT}" \
            --arg description "Deploy ${SITE_NAME} to ${ENVIRONMENT}" \
            '{
              ref: $ref,
              environment: $environment,
              description: $description,
              auto_merge: false,
              required_contexts: [],
              transient_environment: true
            }' 2>&1)

          if [ $? -ne 0 ]; then
            echo "::error::Failed to construct deployment payload with jq"
            echo "$PAYLOAD"
            exit 1
          fi
        else
          PAYLOAD=$(jq -n \
            --arg ref "${{ github.event.pull_request.head.sha || github.sha }}" \
            --arg environment "${ENVIRONMENT}" \
            --arg description "Deploy ${SITE_NAME} to ${ENVIRONMENT}" \
            '{
              ref: $ref,
              environment: $environment,
              description: $description,
              auto_merge: false,
              required_contexts: []
            }' 2>&1)

          if [ $? -ne 0 ]; then
            echo "::error::Failed to construct deployment payload with jq"
            echo "$PAYLOAD"
            exit 1
          fi
        fi

        # Validate payload is not empty
        if [ -z "$PAYLOAD" ]; then
          echo "::error::Deployment payload is empty"
          exit 1
        fi

        DEPLOYMENT_RESPONSE=$(gh api repos/${{ github.repository }}/deployments \
          -X POST \
          --input - <<< "$PAYLOAD" 2>&1)

        # Check if gh api command succeeded
        if [ $? -ne 0 ]; then
          echo "::error::GitHub API call failed to create deployment"
          echo "$DEPLOYMENT_RESPONSE"
          exit 1
        fi

        # Validate response is valid JSON
        if ! echo "$DEPLOYMENT_RESPONSE" | jq -e . >/dev/null 2>&1; then
          echo "::error::Invalid JSON response from deployment creation"
          echo "$DEPLOYMENT_RESPONSE"
          exit 1
        fi

        # Check for API error messages
        ERROR_MESSAGE=$(echo "$DEPLOYMENT_RESPONSE" | jq -r '.message // empty')
        if [ -n "$ERROR_MESSAGE" ]; then
          echo "::error::GitHub API error: $ERROR_MESSAGE"
          echo "$DEPLOYMENT_RESPONSE"
          exit 1
        fi

        DEPLOYMENT_ID=$(echo "$DEPLOYMENT_RESPONSE" | jq -r '.id')

        if [ "$DEPLOYMENT_ID" = "null" ] || [ -z "$DEPLOYMENT_ID" ]; then
          echo "::error::Failed to create deployment - no deployment ID in response"
          echo "$DEPLOYMENT_RESPONSE"
          exit 1
        fi

        STATUS_RESPONSE=$(gh api repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses \
          -X POST \
          -f state="success" \
          -f environment_url="${{ inputs.environment_url }}" \
          -f log_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f description="Deployment successful" 2>&1)

        # Check if gh api command succeeded
        if [ $? -ne 0 ]; then
          echo "::error::GitHub API call failed to create deployment status"
          echo "$STATUS_RESPONSE"
          exit 1
        fi

        # Validate response is valid JSON
        if ! echo "$STATUS_RESPONSE" | jq -e . >/dev/null 2>&1; then
          echo "::error::Invalid JSON response from status creation"
          echo "$STATUS_RESPONSE"
          exit 1
        fi

        # Check for API error messages
        ERROR_MESSAGE=$(echo "$STATUS_RESPONSE" | jq -r '.message // empty')
        if [ -n "$ERROR_MESSAGE" ]; then
          echo "::error::GitHub API error: $ERROR_MESSAGE"
          echo "$STATUS_RESPONSE"
          exit 1
        fi

        STATUS_ID=$(echo "$STATUS_RESPONSE" | jq -r '.id')

        if [ "$STATUS_ID" = "null" ] || [ -z "$STATUS_ID" ]; then
          echo "::error::Failed to create deployment status - no status ID in response"
          echo "$STATUS_RESPONSE"
          exit 1
        fi

        echo "::notice::Created deployment $DEPLOYMENT_ID with status $STATUS_ID"
