#!/usr/bin/env bash
# Stop automated QA server for budget app
# Kills tmux session but leaves Firebase emulators running (shared resource)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUDGET_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TMUX_SESSION="qa-budget"
ENV_FILE="$BUDGET_DIR/site/.env"

echo "========================================="
echo "Budget App - Stopping QA Server"
echo "========================================="
echo ""

# Check if tmux session exists
if ! tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
  echo "✓ tmux session '$TMUX_SESSION' not running"
else
  echo "Stopping tmux session '$TMUX_SESSION'..."
  # Kill the tmux session (this stops finparse and frontend)
  tmux kill-session -t "$TMUX_SESSION" 2>/dev/null || true
  echo "✓ tmux session stopped"
fi

# Clean up auto-generated .env file
if [[ -f "$ENV_FILE" ]]; then
  if grep -q "Auto-generated by dev-qa.sh" "$ENV_FILE" 2>/dev/null; then
    echo "Removing auto-generated .env file..."
    rm -f "$ENV_FILE"
    echo "✓ Auto-generated .env removed"

    # Restore backup if it exists
    LATEST_BACKUP=$(ls -t "${ENV_FILE}.backup."* 2>/dev/null | head -n1 || true)
    if [[ -n "$LATEST_BACKUP" ]]; then
      echo "Restoring backup: $LATEST_BACKUP"
      mv "$LATEST_BACKUP" "$ENV_FILE"
      echo "✓ Backup restored"
    fi
  else
    echo "✓ Preserving user .env file (not auto-generated)"
  fi
fi

echo ""
echo "Note: Firebase emulators are shared and remain running."
echo "To stop emulators:"
echo "  infrastructure/scripts/stop-emulators.sh"
echo ""
