#!/usr/bin/env bash
# Integration test for generate-qa-env.sh
# Tests that the script correctly generates .env files with required variables

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BUDGET_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
SITE_DIR="$BUDGET_DIR/site"

TEST_ENV_FILE="$SITE_DIR/.env.test"
GENERATE_SCRIPT="$SITE_DIR/scripts/generate-qa-env.sh"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Test counters
TESTS_RUN=0
TESTS_PASSED=0
TESTS_FAILED=0

# Test result tracking
test_pass() {
  TESTS_PASSED=$((TESTS_PASSED + 1))
  echo -e "${GREEN}✓${NC} $1"
}

test_fail() {
  TESTS_FAILED=$((TESTS_FAILED + 1))
  echo -e "${RED}✗${NC} $1"
  if [[ -n "${2:-}" ]]; then
    echo -e "  ${YELLOW}Details:${NC} $2"
  fi
}

# Cleanup function
cleanup() {
  rm -f "$TEST_ENV_FILE"
  rm -f "${TEST_ENV_FILE}.backup."* 2>/dev/null || true
}

trap cleanup EXIT

echo "========================================="
echo "Testing generate-qa-env.sh"
echo "========================================="
echo ""

# Test 1: Script exists and is executable
TESTS_RUN=$((TESTS_RUN + 1))
if [[ -x "$GENERATE_SCRIPT" ]]; then
  test_pass "Script exists and is executable"
else
  test_fail "Script exists and is executable" "File not found or not executable: $GENERATE_SCRIPT"
fi

# Test 2: Script generates .env file
TESTS_RUN=$((TESTS_RUN + 1))
cd "$SITE_DIR"
if ENV_FILE="$TEST_ENV_FILE" bash "$GENERATE_SCRIPT" 9099 8081 9199 demo-test >/dev/null 2>&1; then
  if [[ -f "$TEST_ENV_FILE" ]]; then
    test_pass "Script generates .env file"
  else
    test_fail "Script generates .env file" ".env file not created at $TEST_ENV_FILE"
  fi
else
  test_fail "Script generates .env file" "Script execution failed"
fi

# Test 3: Generated file contains auto-generated marker
TESTS_RUN=$((TESTS_RUN + 1))
if grep -q "Auto-generated by dev-qa.sh" "$TEST_ENV_FILE" 2>/dev/null; then
  test_pass "Generated file contains auto-generated marker"
else
  test_fail "Generated file contains auto-generated marker"
fi

# Test 4: Required emulator variables are present
TESTS_RUN=$((TESTS_RUN + 1))
REQUIRED_VARS=(
  "VITE_USE_FIREBASE_EMULATOR=true"
  "VITE_FIREBASE_EMULATOR_AUTH_PORT=9099"
  "VITE_FIREBASE_EMULATOR_FIRESTORE_PORT=8081"
  "VITE_FIREBASE_EMULATOR_STORAGE_PORT=9199"
)

MISSING_VARS=()
for var in "${REQUIRED_VARS[@]}"; do
  if ! grep -q "^${var}" "$TEST_ENV_FILE" 2>/dev/null; then
    MISSING_VARS+=("$var")
  fi
done

if [[ ${#MISSING_VARS[@]} -eq 0 ]]; then
  test_pass "All required emulator variables are present"
else
  test_fail "All required emulator variables are present" "Missing: ${MISSING_VARS[*]}"
fi

# Test 5: Required Firebase config variables are present
TESTS_RUN=$((TESTS_RUN + 1))
REQUIRED_CONFIG_VARS=(
  "VITE_FIREBASE_PROJECT_ID"
  "VITE_FIREBASE_API_KEY"
  "VITE_FIREBASE_AUTH_DOMAIN"
  "VITE_FIREBASE_STORAGE_BUCKET"
  "VITE_FIREBASE_MESSAGING_SENDER_ID"
  "VITE_FIREBASE_APP_ID"
)

MISSING_CONFIG=()
for var in "${REQUIRED_CONFIG_VARS[@]}"; do
  if ! grep -q "^${var}=" "$TEST_ENV_FILE" 2>/dev/null; then
    MISSING_CONFIG+=("$var")
  fi
done

if [[ ${#MISSING_CONFIG[@]} -eq 0 ]]; then
  test_pass "All required Firebase config variables are present"
else
  test_fail "All required Firebase config variables are present" "Missing: ${MISSING_CONFIG[*]}"
fi

# Test 6: Script uses custom ports when provided
TESTS_RUN=$((TESTS_RUN + 1))
rm -f "$TEST_ENV_FILE"
if ENV_FILE="$TEST_ENV_FILE" bash "$GENERATE_SCRIPT" 9999 8888 9777 custom-project >/dev/null 2>&1; then
  if grep -q "VITE_FIREBASE_EMULATOR_AUTH_PORT=9999" "$TEST_ENV_FILE" && \
     grep -q "VITE_FIREBASE_EMULATOR_FIRESTORE_PORT=8888" "$TEST_ENV_FILE" && \
     grep -q "VITE_FIREBASE_EMULATOR_STORAGE_PORT=9777" "$TEST_ENV_FILE" && \
     grep -q "VITE_FIREBASE_PROJECT_ID=custom-project" "$TEST_ENV_FILE"; then
    test_pass "Script uses custom ports and project ID when provided"
  else
    test_fail "Script uses custom ports and project ID when provided"
  fi
else
  test_fail "Script uses custom ports and project ID when provided"
fi

# Test 7: Script backs up existing user .env file
TESTS_RUN=$((TESTS_RUN + 1))
rm -f "$TEST_ENV_FILE"
rm -f "${TEST_ENV_FILE}.backup."* 2>/dev/null || true
echo "# User custom .env file" > "$TEST_ENV_FILE"
echo "CUSTOM_VAR=value" >> "$TEST_ENV_FILE"

if ENV_FILE="$TEST_ENV_FILE" bash "$GENERATE_SCRIPT" 9099 8081 9199 demo-test >/dev/null 2>&1; then
  BACKUP_COUNT=$(find . -maxdepth 1 -name "$(basename "$TEST_ENV_FILE").backup.*" 2>/dev/null | wc -l)
  if [[ $BACKUP_COUNT -eq 1 ]]; then
    BACKUP_FILE=$(find . -maxdepth 1 -name "$(basename "$TEST_ENV_FILE").backup.*" 2>/dev/null | head -n1)
    if grep -q "CUSTOM_VAR=value" "$BACKUP_FILE"; then
      test_pass "Script backs up existing user .env file"
    else
      test_fail "Script backs up existing user .env file" "Backup does not contain original content"
    fi
  else
    test_fail "Script backs up existing user .env file" "Expected 1 backup, found $BACKUP_COUNT"
  fi
else
  test_fail "Script backs up existing user .env file"
fi

# Test 8: Script does not backup auto-generated .env files
TESTS_RUN=$((TESTS_RUN + 1))
rm -f "$TEST_ENV_FILE"
rm -f "${TEST_ENV_FILE}.backup."* 2>/dev/null || true

# Create auto-generated .env
ENV_FILE="$TEST_ENV_FILE" bash "$GENERATE_SCRIPT" 9099 8081 9199 demo-test >/dev/null 2>&1

# Run script again
if ENV_FILE="$TEST_ENV_FILE" bash "$GENERATE_SCRIPT" 9099 8081 9199 demo-test >/dev/null 2>&1; then
  BACKUP_COUNT=$(find . -maxdepth 1 -name "$(basename "$TEST_ENV_FILE").backup.*" 2>/dev/null | wc -l)
  if [[ $BACKUP_COUNT -eq 0 ]]; then
    test_pass "Script does not backup auto-generated .env files"
  else
    test_fail "Script does not backup auto-generated .env files" "Found $BACKUP_COUNT backups"
  fi
else
  test_fail "Script does not backup auto-generated .env files"
fi

echo ""
echo "========================================="
echo "Test Results"
echo "========================================="
echo "Tests run:    $TESTS_RUN"
echo -e "Tests passed: ${GREEN}$TESTS_PASSED${NC}"
if [[ $TESTS_FAILED -gt 0 ]]; then
  echo -e "Tests failed: ${RED}$TESTS_FAILED${NC}"
else
  echo -e "Tests failed: $TESTS_FAILED"
fi
echo ""

if [[ $TESTS_FAILED -eq 0 ]]; then
  echo -e "${GREEN}✓ All tests passed!${NC}"
  exit 0
else
  echo -e "${RED}✗ Some tests failed${NC}"
  exit 1
fi
