#!/usr/bin/env bash
# Generate shell variables from firebase.json emulator ports
# This keeps firebase.json as the single source of truth for port configuration

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FIREBASE_JSON="${REPO_ROOT}/firebase.json"

# Validate firebase.json exists
if [ ! -f "$FIREBASE_JSON" ]; then
  echo "ERROR: firebase.json not found at $FIREBASE_JSON" >&2
  exit 1
fi

# Extract ports using jq and output to stdout
# This can be sourced by other scripts via: source <(generate-firebase-ports.sh)
cat <<EOF
# Auto-generated from firebase.json - DO NOT EDIT MANUALLY
# Source of truth: firebase.json
# Generated by: infrastructure/scripts/generate-firebase-ports.sh

AUTH_PORT=$(jq -r '.emulators.auth.port' "$FIREBASE_JSON")
FIRESTORE_PORT=$(jq -r '.emulators.firestore.port' "$FIREBASE_JSON")
STORAGE_PORT=$(jq -r '.emulators.storage.port' "$FIREBASE_JSON")
UI_PORT=$(jq -r '.emulators.ui.port' "$FIREBASE_JSON")
EOF
