#!/bin/bash
#
# Inject Firebase Configuration into JavaScript File
#
# This script retrieves Firebase configuration and injects it into the
# firebase-config.js file, replacing the placeholder values.
#
# Usage:
#   ./scripts/inject-firebase-config.sh <path-to-firebase-config.js> [PROJECT_ID]
#
# Requirements:
#   - gcloud CLI authenticated with access to Firebase
#   - jq installed
#   - get-firebase-config.sh in the same directory
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check arguments
if [ $# -lt 1 ]; then
    echo -e "${RED}Error: Missing required argument${NC}" >&2
    echo "Usage: $0 <path-to-firebase-config.js> [PROJECT_ID]" >&2
    exit 1
fi

CONFIG_FILE="$1"
PROJECT_ID="${2:-$(gcloud config get-value project 2>/dev/null)}"

if [ ! -f "$CONFIG_FILE" ]; then
    echo -e "${RED}Error: Config file not found: ${CONFIG_FILE}${NC}" >&2
    exit 1
fi

echo -e "${YELLOW}Injecting Firebase configuration into: ${CONFIG_FILE}${NC}"

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Get Firebase config
echo -e "${YELLOW}Fetching Firebase configuration...${NC}"
FIREBASE_CONFIG=$("${SCRIPT_DIR}/get-firebase-config.sh" "$PROJECT_ID")

# Extract values
API_KEY=$(echo "$FIREBASE_CONFIG" | jq -r '.apiKey')
AUTH_DOMAIN=$(echo "$FIREBASE_CONFIG" | jq -r '.authDomain')
PROJECT_ID_VALUE=$(echo "$FIREBASE_CONFIG" | jq -r '.projectId')
STORAGE_BUCKET=$(echo "$FIREBASE_CONFIG" | jq -r '.storageBucket')
MESSAGING_SENDER_ID=$(echo "$FIREBASE_CONFIG" | jq -r '.messagingSenderId')
APP_ID=$(echo "$FIREBASE_CONFIG" | jq -r '.appId')

# Create the new config content
cat > "$CONFIG_FILE" <<EOF
/**
 * Firebase Configuration
 *
 * This configuration is safe to expose publicly as it only identifies
 * the Firebase project. Access control is managed via Firebase Storage
 * security rules (storage.rules).
 *
 * Auto-generated by inject-firebase-config.sh
 */

export const firebaseConfig = {
  apiKey: "${API_KEY}",
  authDomain: "${AUTH_DOMAIN}",
  projectId: "${PROJECT_ID_VALUE}",
  storageBucket: "${STORAGE_BUCKET}",
  messagingSenderId: "${MESSAGING_SENDER_ID}",
  appId: "${APP_ID}"
};
EOF

echo -e "${GREEN}✓ Firebase configuration injected successfully${NC}"
echo -e "${GREEN}  Project: ${PROJECT_ID_VALUE}${NC}"
echo -e "${GREEN}  Storage Bucket: ${STORAGE_BUCKET}${NC}"
