name: 'Update GitHub Deployment Status'
description: 'Updates the status of an existing GitHub deployment'
inputs:
  deployment_id:
    description: 'The ID of the deployment to update'
    required: true
  state:
    description: 'The state to set (success, failure, error, inactive, pending)'
    required: true
  environment_url:
    description: 'URL of the deployment'
    required: true
  description:
    description: 'Description of the deployment status'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Update deployment status
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        DEPLOYMENT_ID: ${{ inputs.deployment_id }}
        STATE: ${{ inputs.state }}
        ENVIRONMENT_URL: ${{ inputs.environment_url }}
        DESCRIPTION: ${{ inputs.description }}
      run: |
        set -euo pipefail

        # Validate inputs
        if [ -z "${DEPLOYMENT_ID// /}" ]; then
          echo "::error::deployment_id input is empty or contains only whitespace"
          exit 1
        fi

        if [ -z "${STATE// /}" ]; then
          echo "::error::state input is empty or contains only whitespace"
          exit 1
        fi

        # Validate URL format if provided - must be valid Firebase Hosting URL
        # Pattern: https://<subdomain>.web.app (no consecutive dots, valid DNS chars)
        if [ -n "${ENVIRONMENT_URL// /}" ]; then
          if ! echo "$ENVIRONMENT_URL" | grep -qE '^https://[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*\.web\.app$'; then
            echo "::error::Invalid URL format: $ENVIRONMENT_URL"
            echo "::error::Expected format: https://<subdomain>.web.app (lowercase, no consecutive dots)"
            exit 1
          fi
        fi

        # Set default description if not provided
        if [ -z "${DESCRIPTION}" ]; then
          case "$STATE" in
            success)
              DESCRIPTION="Deployment successful"
              ;;
            failure)
              DESCRIPTION="Deployment failed"
              ;;
            error)
              DESCRIPTION="Deployment error"
              ;;
            inactive)
              DESCRIPTION="Deployment inactive"
              ;;
            pending)
              DESCRIPTION="Deployment pending"
              ;;
            *)
              DESCRIPTION="Deployment status: $STATE"
              ;;
          esac
        fi

        # Update deployment status
        set +e  # Disable exit on error to capture exit code
        STATUS_RESPONSE=$(gh api repos/${{ github.repository }}/deployments/${DEPLOYMENT_ID}/statuses \
          -X POST \
          -f state="${STATE}" \
          -f environment_url="${ENVIRONMENT_URL}" \
          -f log_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f description="${DESCRIPTION}" 2>&1)
        GH_EXIT_CODE=$?
        set -e  # Re-enable exit on error

        if [ $GH_EXIT_CODE -ne 0 ]; then
          echo "::error::GitHub API call failed to update deployment status"
          echo "$STATUS_RESPONSE"
          exit 1
        fi

        # Validate response is valid JSON
        if ! echo "$STATUS_RESPONSE" | jq -e . >/dev/null 2>&1; then
          echo "::error::Invalid JSON response from status update"
          echo "$STATUS_RESPONSE"
          exit 1
        fi

        # Check for API error messages
        ERROR_MESSAGE=$(echo "$STATUS_RESPONSE" | jq -r '.message // empty')
        if [ -n "$ERROR_MESSAGE" ]; then
          echo "::error::GitHub API error: $ERROR_MESSAGE"
          echo "$STATUS_RESPONSE"
          exit 1
        fi

        STATUS_ID=$(echo "$STATUS_RESPONSE" | jq -r '.id')

        if [ "$STATUS_ID" = "null" ] || [ -z "$STATUS_ID" ]; then
          echo "::error::Failed to update deployment status - no status ID in response"
          echo "$STATUS_RESPONSE"
          exit 1
        fi

        echo "::notice::Updated deployment $DEPLOYMENT_ID to state '$STATE' (status ID: $STATUS_ID)"
