#!/usr/bin/env bash
# Generate .env file for QA environment with Firebase emulator configuration
# This script creates a temporary .env file to allow the frontend to connect to emulators

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SITE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Allow ENV_FILE to be overridden for testing
ENV_FILE="${ENV_FILE:-$SITE_DIR/.env}"

# Parse arguments
AUTH_PORT="${1:-9099}"
FIRESTORE_PORT="${2:-8081}"
STORAGE_PORT="${3:-9199}"
PROJECT_ID="${4:-demo-test}"

echo "Generating QA environment configuration..."

# Backup existing user .env if it exists and is not auto-generated
if [[ -f "$ENV_FILE" ]]; then
  if ! grep -q "Auto-generated by dev-qa.sh" "$ENV_FILE" 2>/dev/null; then
    BACKUP_FILE="${ENV_FILE}.backup.$(date +%s)"
    echo "⚠️  Backing up existing .env to $BACKUP_FILE"
    cp "$ENV_FILE" "$BACKUP_FILE"
  else
    echo "Removing previous auto-generated .env file"
    rm -f "$ENV_FILE"
  fi
fi

# Generate .env file with emulator configuration
cat > "$ENV_FILE" << EOF
# Auto-generated by dev-qa.sh - DO NOT EDIT
# This file is automatically created for QA environment and will be cleaned up by stop-qa.sh

# Firebase Emulator Configuration
VITE_USE_FIREBASE_EMULATOR=true
VITE_FIREBASE_EMULATOR_AUTH_PORT=$AUTH_PORT
VITE_FIREBASE_EMULATOR_FIRESTORE_PORT=$FIRESTORE_PORT
VITE_FIREBASE_EMULATOR_STORAGE_PORT=$STORAGE_PORT

# Firebase Project Configuration (dummy values for emulator)
VITE_FIREBASE_PROJECT_ID=$PROJECT_ID
VITE_FIREBASE_API_KEY=dummy-api-key-for-emulator
VITE_FIREBASE_AUTH_DOMAIN=$PROJECT_ID.firebaseapp.com
VITE_FIREBASE_STORAGE_BUCKET=$PROJECT_ID.appspot.com
VITE_FIREBASE_MESSAGING_SENDER_ID=000000000000
VITE_FIREBASE_APP_ID=1:000000000000:web:0000000000000000000000
EOF

echo "✓ Generated .env file for QA environment"
echo "  - Using Firebase emulators (localhost)"
echo "  - Auth port: $AUTH_PORT"
echo "  - Firestore port: $FIRESTORE_PORT"
echo "  - Storage port: $STORAGE_PORT"
echo "  - Project ID: $PROJECT_ID"
